<h1>How to Become a Ninja</h1>
<main>
  <h2>Learn the Art of Moving Stealthily</h2>
  <h3>How to Hide in Plain Sight</h3>
  <h3>How to Climb a Wall</h3>

  <h2>Learn the Art of Battle</h2>
  <h3>How to Strengthen your Body</h3>
  <h3>How to Fight like a Ninja</h3>

  <h2>Learn the Art of Living with Honor</h2>
  <h3>How to Breathe Properly</h3>
  <h3>How to Simplify your Life</h3>
</main>

//"h" tags (headers) should only be used with semantic meaning in mind, NOT just for their size//
//Screen readers depend on these to give summaries to the user, so they have to be used appropriately//
//There should only ever be 1 h1 tag to describe the content of the entire page//
//Create a hierarchy of content using larger header sizes (h2..) and scaling down by 1 (..h3..h3..h5, etc.) for subsections//
